Repository TeamTouchDown/perflow-backend, pull requests merged in 2024-12, with the labels that each got.

#4 [setting] #3 백엔드 프로젝트 초기 설정
  perflow-backend/.gitattributes
  perflow-backend/build.gradle
  perflow-backend/gradle/wrapper/gradle-wrapper.jar
  perflow-backend/gradle/wrapper/gradle-wrapper.properties
  perflow-backend/gradlew
  perflow-backend/gradlew.bat
  perflow-backend/settings.gradle
  perflow-backend/src/main/java/com/touchdown/perflowbackend/PerflowBackendApplication.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/CustomException.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorResponse.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/GlobalExceptionHandler.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/resources/application.yml
  perflow-backend/src/test/java/com/touchdown/perflowbackend/PerflowBackendApplicationTests.java
Labels: ⚙ Setting

#13 [setting] : #12 gitignore 생성
  .gitignore
Labels: ⚙ Setting

#15 [Setting] : #5 ~ #11 ddl로 추출한 엔터티 패키지 구조 생성
  perflow-backend/src/main/java/com/touchdown/perflowbackend/aiperfosummary/command/domain/aggregate/AiPerfoSummary.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/domain/aggregate/Announcement.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/annual/command/domain/aggregate/Annual.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/appoint/command/domain/aggregate/Appoint.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approveline/command/domain/aggregate/ApproveLine.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approvesbj/command/domain/aggregate/ApproveSbj.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/attendance/command/domain/aggregate/Attendance.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/command/domain/aggregate/Authority.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/company/command/domain/aggregate/Company.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/department/command/domain/aggregate/Department.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/doc/command/domain/aggregate/Doc.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/docshareobj/command/domain/aggregate/DocShareObj.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/favtemplate/command/domain/aggregate/FavTemplate.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/file/command/domain/aggregate/File.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/graderatio/command/domain/aggregate/GradeRatio.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hrperfo/command/domain/aggregate/HrPerfo.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hrperfohistory/command/domain/aggregate/HrPerfoHistory.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hrperfoinquiry/command/domain/aggregate/HrPerfoInquiry.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/job/command/domain/aggregate/Job.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/kpi/command/domain/aggregate/Kpi.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/kpiprogressstatus/command/domain/aggregate/KpiProgressStatus.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/kpistatus/command/domain/aggregate/KpiStatus.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/leave/command/domain/aggregate/Leave.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/command/domain/aggregate/Menu.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/overtime/command/domain/aggregate/Overtime.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payroll/command/domain/aggregate/Payroll.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfo/command/domain/aggregate/Perfo.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfoquestion/command/domain/aggregate/Perfoquestion.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/position/command/domain/aggregate/Position.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/severancepay/command/domain/aggregate/SeverancePay.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/teamplate/command/domain/aggregate/Template.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/templatefield/command/domain/aggregate/TemplateField.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/travel/command/domain/aggregate/Travel.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/weight/command/domain/aggregate/Weight.java
  perflow-backend/src/main/resources/application.yml
Labels: ⚙ Setting

#16 [feat/baseentity]: BaseEntity 생성
  perflow-backend/src/main/java/com/touchdown/perflowbackend/PerflowBackendApplication.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/BaseEntity.java
Labels: ✨ Feat

#17 [setting]: ddl 수정에 따른 변경사항 #9
  perflow-backend/gradlew
  perflow-backend/src/main/java/com/touchdown/perflowbackend/annual/command/domain/aggregate/Annual.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/overtime/command/domain/aggregate/Overtime.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/vacation/command/domain/aggregate/Vacation.java
Labels: ⚙ Setting

#20 Setting/#18 결재 엔터티 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/annual/command/domain/aggregate/Annual.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/ApproveLine.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/ApproveSbj.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/Doc.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/DocShareObj.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/FavTemplate.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/Status.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/Template.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/TemplateField.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/file/command/domain/aggregate/File.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/overtime/command/domain/aggregate/Overtime.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/travel/command/domain/aggregate/Travel.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/vacation/command/domain/aggregate/Vacation.java
Labels: ⚙ Setting

#22 [refactor/feat] : #19 급여 관련 엔터티 수정 및 status 추가
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payroll/command/domain/aggregate/Payroll.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payroll/command/domain/aggregate/SeverancePay.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payroll/command/domain/aggregate/Status.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/severancepay/command/domain/aggregate/SeverancePay.java
Labels: ✨ Feat, 🔨 Refactor

#24 [setting]: #9 workAttitude 패키지 생성
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/BaseEntity.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Annual.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Attendance.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Overtime.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Status.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Travel.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Vacation.java
  perflow-backend/src/main/resources/application.yml
Labels: ⚙ Setting

#28 chore: #26 부서 엔터티 상위부서 nullable로 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/department/command/domain/aggregate/Department.java
Labels: 💻 Chore

#33 [setting/hr] #29 인사정보 관리 패키지 구조 변경
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/domain/aggregate/Announcement.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/ApproveSbj.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/DocShareObj.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Appoint.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Authority.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Company.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Department.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Job.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Position.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/command/domain/aggregate/Menu.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfoquestion/command/domain/aggregate/Perfoquestion.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/weight/command/domain/aggregate/Weight.java
Labels: ⚙ Setting

#35 [feat/hr] #25 사원 정보 등록 기능 구현
  perflow-backend/build.gradle
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/controller/EmployeeCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeeRegisterDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/mapper/EmployeeMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmployeeCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/EmployeeStatus.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/repository/EmployeeCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/infrastructure/repository/JpaEmployeeCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/repository/DepartmentCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/repository/JobCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/repository/PositionCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/infrastructure/repository/JpaDepartmentCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/infrastructure/repository/JpaJobCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/infrastructure/repository/JpaPositionCommandRepository.java
  perflow-backend/src/main/resources/application.yml
Labels: ✨ Feat

#40 [feat/announcement]: 공지 생성 기능 구현 및 Swagger API 추가
  perflow-backend/build.gradle
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/application/controller/AnnouncementCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/application/dto/AnnouncementRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/application/service/AnnouncementCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/domain/aggregate/Announcement.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/domain/repository/AnnouncementCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/infrastructure/repository/JpaAnnouncementRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/mapper/AnnouncementMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/config/SwaggerConfig.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/repository/EmployeeCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
  perflow-backend/src/main/resources/application.yml
Labels: ✨ Feat

#45 [feat/payment/#23] : 엑셀 템플릿 구현
  perflow-backend/build.gradle
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/repository/EmployeeCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/Payroll.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePay.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/Status.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/ExcelTemplateQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/ExcelTemplateQueryService.java
Labels: ✨ Feat

#46 [feat/travel/#27]: 출장 controller 사원 부분 및 조회 service 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/infrastructure/repository/JpaApproveCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/repository/ApproveCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/controller/WorkAttitudeTravelCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/dto/WorkAttitudeTravelRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeTravelCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Annual.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Attendance.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Overtime.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Status.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Travel.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Vacation.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/repository/WorkAttitudeTravelCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/infrastructure/repository/JpaWorkAttitudeRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/mapper/WorkAttitudeTravelMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/WorkAttitudeTravelResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttributeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeQueryService.java
  perflow-backend/src/main/resources/application.yml
Labels: ✨ Feat

#44 [feat/approval/#21]: 서식 생성 API 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/controller/TemplateCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/dto/TemplateCreateRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/dto/TemplateCreateResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/dto/TemplateFieldCreateRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/service/TemplateCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/ApproveLine.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/ApproveSbj.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/Doc.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/DocShareObj.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/FavTemplate.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/FieldType.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/Status.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/Template.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/TemplateField.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/repository/ApproveCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/repository/FieldTypeCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/repository/TemplateCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/repository/TemplateFieldCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/infrastructure/repository/JpaApproveCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/infrastructure/repository/JpaFieldTypeCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/infrastructure/repository/JpaTemplateCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/infrastructure/repository/JpaTemplateFieldCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/mapper/TemplateFieldMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/mapper/TemplateMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/Status.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/TemplateField.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/infrastructure/repository/JpaApproveCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/repository/ApproveCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/file/command/domain/aggregate/File.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/application/service/PersonalKPIQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/domain/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeTravelCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Annual.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Overtime.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Travel.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Vacation.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/mapper/WorkAttitudeTravelMapper.java
Labels: ✨ Feat

#51 [feat/hr] #36 Spring Security 기본 설정 구현, jwt 사용한 로그인 기능 구현
  perflow-backend/build.gradle
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/controller/EmployeeCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeeLoginRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeeLoginResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeePwdRegisterDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmployeeCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/config/SecurityConfig.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/filter/JwtFilter.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/handler/JwtAccessDeniedHandler.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/handler/JwtAuthenticationEntryPoint.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/service/CustomEmployeeDetailsService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/util/CustomEmployDetail.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/util/JwtTokenProvider.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/util/JwtUtil.java
  perflow-backend/src/main/resources/application.yml
Labels: ✨ Feat

#55 [chore] : #54 Swagger 설정 FilterChain에서 제외 처리
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/config/SecurityConfig.java
Labels: 💻 Chore

#56 [feat/perfo] #37 개인 KPI 조회 기능
  perflow-backend/build.gradle
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/application/controller/PerfomanceKPIController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/application/service/PersonalKPIQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceKPIQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/domain/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPILimitResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIListResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/PersonalKPIQueryService.java
Labels: ✨ Feat

#59 [refactor/yml]: yml 설정 수정
  perflow-backend/src/main/resources/application.yml
Labels: 🔨 Refactor

#63 [feat/payment/#49] : 급여대장 수정 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/ExcelTemplateCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/PayrollCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/ExcelTemplateCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/PayrollCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/Payroll.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePay.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/Status.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/repository/PayrollCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/infrastructure/repository/JpaPayrollRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/ExcelTemplateQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/ExcelTemplateQueryService.java
Labels: ✨ Feat

#65 [feat/approval/#50] 서식 목록/상세 조회 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/controller/TemplateCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/service/TemplateCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/ApproveLine.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/Doc.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/FieldType.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/Template.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/TemplateField.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/mapper/TemplateFieldMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/mapper/TemplateMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/controller/TemplateQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/dto/TemplateDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/dto/TemplateFieldResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/dto/TemplateListResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/repository/TemplateQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/service/TemplateQueryService.java
Labels: ✨ Feat

#67 [feat/travel/#53]: 직원 출장 cqrs 구조
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/controller/WorkAttitudeTravelCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeTravelCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Travel.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/repository/WorkAttitudeTravelCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/infrastructure/repository/JpaWorkAttitudeRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/mapper/WorkAttitudeTravelMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeTravelQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/WorkAttitudeTravelResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttributeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttributeTravelQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeTravelQueryService.java
Labels: ✨ Feat

#69 [feat/perfo/#60]: 개인 KPI CRUD 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceKPICommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/KPIDetailRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/KPICommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Kpi.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/KpiCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/KpiKpiRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/PersonalKPIQueryService.java
Labels: ✨ Feat

#71 [feat/perfo/#70]: 팀 KPI CRUD 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceKPIPersonalCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceKPITeamCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/KPICommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIPersonalQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPITeamQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
Labels: ✨ Feat

#74 [feat/hr] #52 SpringSecurity
  perflow-backend/build.gradle
  perflow-backend/docker-compose.yml
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/config/RedisConfig.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/controller/EmployeeCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeeLogoutRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/TokenResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmployeeCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/config/SecurityConfig.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/redis/BlackAccessToken.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/redis/WhiteRefreshToken.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/repository/BlackAccessTokenRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/repository/WhiteRefreshTokenRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/util/EmployeeUtil.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/util/JwtTokenProvider.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/util/JwtUtil.java
  perflow-backend/src/main/resources/application.yml
Labels: ✨ Feat

#75 [feat/approval/#66] 서식 수정, 서식 단일 삭제, 서식 선택 삭제 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/controller/TemplateCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/dto/TemplateFieldUpdateRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/dto/TemplateUpdateRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/dto/TemplatesDeleteRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/service/TemplateCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/Template.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/TemplateField.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/repository/ApproveCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/repository/FieldTypeCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/repository/TemplateCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/mapper/TemplateFieldMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/mapper/TemplateMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/controller/TemplateQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
Labels: ✨ Feat

#80 [feat/travel/#53]: 출장 crud 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/controller/WorkAttitudeTravelCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/dto/WorkAttitudeTravelCommandForTeamLeaderRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeTravelCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Travel.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/repository/WorkAttitudeTravelCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeTravelQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttributeTravelQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeTravelQueryService.java
Labels: ✨ Feat

#83 [feat/hr/#81] : 부서 조회, 해당 부서에 속한 사원 조회 api 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/Mapper/EmployeeMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/controller/EmployeeQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/dto/EmployeeQueryResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/service/EmployeeQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/Mapper/HrMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Department.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/HrQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/dto/DepartmentQueryResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/repository/DepartmentQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/service/HrQueryService.java
Labels: ✨ Feat

#85 [feat/perfo/#72] : 동료 평가 CRU 기능 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceEvaluationColleagueCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/EvalutionDetailDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/EvalutionListDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/EvalutionCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/KPICommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Perfo.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/KpiCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/PerfoCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/PerfoQuestionCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/EvaEvalutionRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/QuestionCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceEvaluationCollagueQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaAnswerResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/EvaQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/EvaQueryService.java
Labels: ✨ Feat

#93 [feat/perfo/#89] :동료 평가 문항 CRUD 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerfomanceEvaluationColleagueQuestionCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceEvaluationColleagueCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreateQuestionRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/UpdateQuestionRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/EvalutionCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Perfoquestion.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/PerfoCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceEvaluationCollagueQuestionQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaQuestionDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaQuestionRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/EvaQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/EvaQueryService.java
Labels: ✨ Feat

#95 [feat/perfo/#94] : 하향 평가 CRU 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceEvaluationDownwardCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreateQuestionRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/EvalutionDetailDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/EvalutionListDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/UpdateQuestionRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceEvaluationDownwardQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaAnswerResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaQuestionDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaQuestionRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPILimitResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIListResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/EvaQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/EvaQueryService.java
Labels: ✨ Feat

#99 [feat/hr] : #90 전체 부서 정보 조회 서비스 로직 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/controller/EmployeeQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/Mapper/HrMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/HrQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/dto/DepartmentListResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/service/HrQueryService.java
Labels: ✨ Feat

#100 [feat/payment] : #64 특정 급여대장 업로드
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/ExcelTemplateCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/ExcelTemplateCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/PayrollCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/Payroll.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/PayrollDetail.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePay.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePayDetail.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/repository/PayrollCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/ExcelTemplateQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/PayrollQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
Labels: ✨ Feat

#105 [feat/overtime]#92: 초과근무 CRUD 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/controller/WorkAttributeOvertimeCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/dto/RetroactiveRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/dto/WorkAttitudeTravelCommandForTeamLeaderRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttributeOvertimeCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Overtime.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/mapper/WorkAttributeOvertimeMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttributeOvertimeQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/WorkAttributeOvertimeForEmployeeResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/WorkAttributeOvertimeForEmployeeSummaryDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/WorkAttributeOvertimeForTeamLeaderSummaryDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttributeOvertimeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttributeOvertimeQueryService.java
Labels: ✨ Feat

#108 [feat/approval/#84] 결재 문서 생성, 나의 결재선 생성
  perflow-backend/build.gradle
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/controller/DocCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/dto/ApproveLineDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/dto/DocCreateRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/dto/MyApproveLineCreateRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/dto/ShareDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/service/DocCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/ApproveLine.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/ApproveSbj.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/ApproveTemplateType.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/ApproveType.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/Doc.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/DocShareObj.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/ObjType.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/SbjType.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/repository/ApproveLineCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/repository/DocCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/infrastructure/repository/JpaApproveLineCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/infrastructure/repository/JpaDocCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/mapper/DocMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/controller/DocQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/dto/MyApproveLineDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/dto/MyApproveLineGroupResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/dto/MyApproveLineResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/repository/ApproveLineQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/repository/DocQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/service/DocQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/service/TemplateQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/Mapper/HrMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/dto/DepartmentQueryResponseDTO.java
Labels: ✨ Feat

#110 [feat/payment/#103] 급여대장 조회
  perflow-backend/build.gradle
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/repository/EmployeeCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/PayrollSpecifications.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/ExcelTemplateQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/PayStubDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/PayrollChartDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/PayrollDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/PayrollDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/PayrollListResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/PayrollResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/PayrollDetailQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/PayrollQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/ExcelTemplateQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
Labels: ✨ Feat

#112 [feat/hr] #102 부서 등록/수정 기능 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/controller/CompanyCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/controller/DepartmentCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/company/CompanyAnnualCountUpdateDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/company/CompanyCreateRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/company/CompanyPaymentDatetimeUpdateDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/company/CompanyUpdateRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/department/DepartmentCreateDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/department/DepartmentUpdateDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/mapper/CompanyMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/mapper/DepartmentMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/service/CompanyCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/service/DepartmentCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Company.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Department.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Job.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Pic.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Position.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/repository/DepartmentCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/repository/PicCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/infrastructure/repository/JpaPicCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/service/HrQueryService.java
Labels: ✨ Feat

#115 [feat/perfo/#98] :인사 평가 CRU 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceEvaluationColleagueQuestionCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceEvaluationDownwardQuestionCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceHumanResourcePerfoCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/HumanResourceCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfo.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfoHistory.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfoStatus.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/HrPerfoCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/HrPerfoHistoryCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/KpiCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/WeightCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/HrPerfoHistoryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/HrPerfoRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/WeightRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceHrPerfoQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/HrPerfoResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/HrPerfoQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/HrPerfoService.java
Labels: ✨ Feat

#119 [feat/payment/#111]: 퇴직금 정보 엑셀 파일로 업로드/다운로드
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/SeveranceExcelTemplateCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/SeverancePayCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/SeveranceExcelTemplateCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/SeverancePayCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePay.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePayDetail.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/repository/SeverancePayCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/infrastructure/repository/JpaSeverancePayRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/SeveranceExcelTemplateQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/SeverancePayQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/PayrollQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/SeverancePayQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeveranceExcelTemplateQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeverancePayQueryService.java
Labels: ✨ Feat

#130 [feat/payment/#124]: 퇴직금 조회
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/PayrollCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/SeverancePayCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/PayrollCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/SeverancePayCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/PayrollDetail.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePayDetail.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/repository/PayrollCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/repository/SeverancePayCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/SeverancePayQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/ExcelTemplateQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeveranceExcelTemplateQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeverancePayQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/ThreeMonthOvertimeDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeOvertimeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeOvertimeQueryService.java
Labels: ✨ Feat

#135 [chore/payment/#134]: 급여대장 리스트 조회 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
Labels: 💻 Chore

#137 [feat/perfo] : #116 인사평가 의의제기 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerfomanceHumanResourceInquiryCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/UpdateInquiryRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/HumanResourceCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfo.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfoHistory.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfoInquiry.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/PassStatus.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/HrPerfoCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/HrPerfoHistoryCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/HrPerfoInquiryCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/HrPerfoInquiryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceHrPerfoInquiryQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/HrPerfoInquiryResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/HrPerfoInquiryQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/HrPerfoInquiryService.java
Labels: ✨ Feat

#140 [chore/payment/#139]: 퇴직금 기간 기준 변경
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeOvertimeQueryRepository.java
Labels: 💻 Chore

#143 [feat/perfo/#138]: 인사 평가 비율 기능 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerfomancceRatioCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreatePerfoRatioRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/RatioCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Weight.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceRatioQueryCommand.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/RatioPerfoResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/WeightQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/RatioQueryService.java
Labels: ✨ Feat

#145 [feat/perfo/#144]: 등급 비율 기능 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerfomancceRatioCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreateGradeRatioRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/RatioCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/GradeRatio.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/GradeCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/GradeRatioRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceRatioQueryCommand.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/RatioGradeResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/GradeRatioQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/WeightQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/RatioQueryService.java
Labels: ✨ Feat

#147 [feat/menu] : #136 menu조회 기능 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/command/domain/aggregate/Menu.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/query/application/controller/MenuQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/query/application/dto/MenuResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/query/application/mapper/MenuMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/query/application/repository/MenuQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/query/application/service/MenuQueryService.java
Labels: ✨ Feat

#148 [feat/perfo/#146]: KPI 최신화, 평가 조정 기능 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceEvaluationPassCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceHumanResourceInquiryCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceKPIPassCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceRatioCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreateKpiPassDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreatePerfoAdjustmentDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/EvalutionCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/KPICommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfoHistory.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Kpi.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiProgressStatus.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/KpiProgressCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/KpiProgressRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
Labels: ✨ Feat

#155 [chore/payment/#153]: 3년간 급여 데이터 조회 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/SeverancePayQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/PayrollChartWithYearDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/PayrollQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
Labels: 💻 Chore

#157 [feat/attitude]:#154 근무시간 페이징 처리
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeAttendanceQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/WorkAttitudeAttendancePageResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeAttendanceQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeAttendanceQueryService.java
Labels: ✨ Feat

#163 [feat/attitude/]#154: 페이징 처리 이전으로 rollback
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeAttendanceQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeAttendanceQueryService.java
Labels: ✨ Feat

#162 [chore/perfo] : #161 Kpi 리스트 호출 기능 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
Labels: 💻 Chore

#165 [ chore/attitude]/#154: 근태 부분 service, controller, repository 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeAttendanceQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeAttendanceQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeAttendanceQueryService.java
Labels: 💻 Chore

#167 [chore/perfo] : #166 Kpi status, 쿼리문 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiCurrentStatus.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
Labels: 💻 Chore

#170 [feat/payment/#169]: 정렬 설정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
Labels: ✨ Feat

#173 [feat/hr] #160 CSV 템플릿 파일 다운로드 기능 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeeCreateDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmployeeCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/EmployeeStatus.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/controller/EmployeeQueryController.java
Labels: ✨ Feat

#176 [feat/hr] : #175 비밀번호 등록 기능 추가 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/controller/EmployeeCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmailService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmployeeCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/util/JwtUtil.java
Labels: ✨ Feat

#178 [chore/perfo] : #177 KPI 조회 시 kpiId 조회 가능 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
Labels: 💻 Chore

#180 [chore/perfo] : #179 KPI 수정 시 상태 변경 추가
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/KPIDetailRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Kpi.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIStatusQueryRepository.java
Labels: 💻 Chore

#182 feat: #181 공지사항 조회 기능 수정 (작성자 검색 기능 삭제, 부서별 필터링 기능 추가)
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/query/controller/AnnouncementQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/query/repository/AnnouncementQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/query/service/AnnouncementQueryService.java
Labels: ✨ Feat, 🔨 Refactor

#185 [chore/perfo] : #184 KPI 수정 시 상태 변경 추가
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
Labels: 💻 Chore

#186 [chore/attitude]/#154: query service, dto 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/WorkAttitudeAttendanceSummaryResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeAttendanceQueryService.java
Labels: 💻 Chore

#191 [feat/perfo] : #187 KPI CRUD 추가 및 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/KPIDetailRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Kpi.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIPersonalQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPITeamQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIDetailResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIPeriodRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
Labels: ✨ Feat

#193 [chore/perfo] : #192 KPI 기간별 조회 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIPersonalQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPITeamQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIPeriodRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
Labels: 💻 Chore

#198 [chore/payment/#197]: 검색기능 조회 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/PayrollSpecifications.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/ExcelTemplateQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
Labels: 💻 Chore

#200 [feat/perfo] : #195 KPI 기간별 조회 구현 및 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIPersonalQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPITeamQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
Labels: ✨ Feat, 💻 Chore

#202 [feat/perfo] : #201 KPI 기간별 조회 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIPersonalQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPITeamQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
Labels: ✨ Feat

#204 [Feat/hr] #190 사원 권한/메뉴 관련 기능 구현
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/application/controller/AuthorityEmployeeCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/application/dto/AuthorityEmployeeRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/application/service/AuthorityEmployeeCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/domain/aggregate/AuthType.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/domain/aggregate/Authority.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/domain/aggregate/AuthorityEmployee.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/domain/aggregate/AuthorityEmployeeId.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/domain/repository/AuthorityEmployeeRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/domain/repository/AuthorityRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/infrastructure/JpaAuthorityEmployeeRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/infrastructure/JpaAuthorityRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/Mapper/EmployeeMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmployeeCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/controller/EmployeeQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/dto/EmployeeQueryResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/service/EmployeeQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/company/CompanyUpdateRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/service/CompanyCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/service/DepartmentCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Authority.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Company.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/HrQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/JobQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/PositionQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/command/domain/aggregate/Menu.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/query/application/dto/MenuResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/config/SecurityConfig.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/util/CustomEmployDetail.java
Labels: ✨ Feat

#207 [refactor/payment/#205]: 급여 명세서 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/PayrollQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeveranceExcelTemplateQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeOvertimeQueryRepository.java
Labels: 🔨 Refactor

#213 [chore/payment/#212]: 타입 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeverancePayQueryService.java
Labels: 💻 Chore

#215 [deploy] : #214 도커파일 생성
  perflow-backend/Dockerfile
Labels: 🌏 Deploy

#219 [chore/perfo/#203]: KPI 기간별 조회 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIPersonalQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPITeamQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
Labels: 💻 Chore

#223 [chore/attitude/]#218: 연차 중복 체크 로직 수정 + 초과근무 로직 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeAnnualCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeVacationCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Annual.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeOvertimeQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeTravelQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeVacationQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeAnnualQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeOvertimeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeAnnualQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeOvertimeQueryService.java
Labels: 💻 Chore

#225 [chore/attitude/#218]: 충돌 해결간 오류 해결
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeVacationCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeOvertimeQueryController.java
Labels: 💻 Chore

#226 [chore/payment/#222]: 연차 식 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/PayrollCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/ExcelTemplateQueryService.java
Labels: 💻 Chore

#235 [feat/attitude/#228] : test code
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/dto/WorkAttitudeAnnualRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeAnnualCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Annual.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/PerflowBackendApplicationTests.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeAnnualCommandServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeApprovalRequestCommandServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeAttendanceCommandServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeOvertimeCommandServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeTravelCommandServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeVacationCommandServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeAnnualQueryServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeAttendanceQueryServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeOvertimeQueryServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeTravelQueryServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeVacationQueryServiceTest.java
Labels: ✨ Feat

#240 [chore/attitude/#239] test code 수정
  perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeOvertimeCommandServiceTest.java
Labels: 💻 Chore

#241 [deploy] workflow 조금 수정
  .github/workflows/main.yml
Labels: 🌏 Deploy, 💻 Chore

#242 [deploy] workflow 진짜 마지막 수정
  .github/workflows/main.yml
Labels: 💻 Chore

#243 [feat/notification] 웹 푸시 알림 기능 개발
  .gitignore
  perflow-backend/build.gradle
  perflow-backend/docker-compose.yml
  perflow-backend/src/main/java/com/touchdown/perflowbackend/PerflowBackendApplication.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/config/FCMConfig.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/config/RabbitMQConfig.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/application/controller/FcmTokenController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/application/dto/FcmTokenRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/application/dto/NotificationMessageDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/application/service/FcmService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/application/service/FcmTokenService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/application/service/NotificationCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/FcmToken.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/RefType.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/repository/FcmTokenRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/repository/NotificationCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/infrastructure/rabbitmq/NotificationListener.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/infrastructure/repository/JpaNotificationRepository.java
  perflow-backend/src/main/resources/application.yml
Labels: ✨ Feat, 💻 Chore

#245 [feat/approval/#211] 수신함 문서 목록 검색 api 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/dto/ApprovalRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/service/ApprovalService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/ApproveSbj.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/aggregate/Doc.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/repository/ApproveLineCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/controller/DocQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/dto/ProcessedDocListResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/repository/DocQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/service/DocQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/specification/DocSpecification.java
  perflow-backend/src/main/resources/application.yml
  perflow-backend/src/test/java/com/touchdown/perflowbackend/approval/command/application/service/DocCommandServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/approval/query/service/DocQueryServiceTest.java
Labels: ✨ Feat

#246 [test/payment/#236]: 테스트 코드 작성
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/PayrollDTO.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/payment/query/service/SeverancePayQueryServiceTest.java
Labels: ✅ Test

#248 [doc] : readme 수정
  README.md
  perflow-backend/src/main/resources/application.yml
Labels: 📃 Docs
