Repository TeamTouchDown/perflow-backend, pull requests merged in 2025-01, with the labels that each got.

#259 workflow에 디버그 추가 main.yml
  .github/workflows/main.yml
Labels: 🐞 Bug

#260 [fix]: docker 파일 수정
  perflow-backend/Dockerfile
Labels: 🐞 Bug

#264 [fix/deploy] : workflow 수정
  .github/workflows/main.yml
Labels: 🐞 Bug

#269 [chore]: #268 이메일 전송 기능 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/controller/EmployeeCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/config/SecurityConfig.java
  perflow-backend/src/main/resources/application.yml
Labels: 💻 Chore

#271 [chore]: #268 비밀번호 등록 이메일 검증 url 배포에 맞게 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmailService.java
Labels: 💻 Chore

#274 [feat/noti]: 결재 문서 알림 기능 연결
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/application/service/DocCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/config/FCMConfig.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/application/service/NotificationCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/query/controller/NotificationQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/query/dto/NotificationResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/query/mapper/NotificationMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/query/repository/NotificationQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/query/service/NotificationQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/security/config/SecurityConfig.java
Labels: ✨ Feat

#277 [feat/attendance/#275] 근태부분 지각, 결근 조회
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/util/DateUtil.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeAttendanceQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/SimpleAttendanceSummaryResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeAttendanceQueryService.java
Labels: ✨ Feat

#282 [test/ann]: 공지사항 관련 테스트 코드 작성
  perflow-backend/src/test/java/com/touchdown/perflowbackend/announcement/command/application/service/AnnouncementCommandServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/announcement/query/service/AnnouncementQueryServiceTest.java
Labels: ✅ Test

#284 [chore/payment/#273]: 여러가지 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/PayrollDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/SeverancePayDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/PayrollQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/SeverancePayQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeveranceExcelTemplateQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeverancePayQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeOvertimeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeOvertimeQueryService.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/payment/query/service/SeverancePayQueryServiceTest.java
Labels: 💻 Chore

#290 [feat/approval/#285] 발신함 문서 목록 검색 api 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/query/controller/DocQueryController.java
Labels: 🐞 Bug, ✨ Feat

#292 [doc] : #291 readme 작성
  README.md
Labels: 📃 Docs

#293 [chore/payment/#289]: 여러가지 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeOvertimeQueryRepository.java
Labels: 💻 Chore

#295 [feat/noti]: 알림 삭제 로직, 공지사항 알림 로직 추가
  perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/application/service/AnnouncementCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/repository/EmployeeCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/application/controller/NotificationCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/application/service/NotificationCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/RefType.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/repository/NotificationCommandRepository.java
Labels: ✨ Feat

#294 [chore/perfo/#249]: 여러가지 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeeCreateDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/department/DepartmentCreateDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerfomanceKPILimitCommandController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreatePerfoAdjustmentDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreateQuestionRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/EvalutionDetailDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/EvalutionListDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/UpdateInquiryRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/UpdateQuestionRequestDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/KPICommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiLimit.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/KpiLimitCommandRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/KpiLimitRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceEvaluationCollagueQuestionQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceEvaluationDownwardQuestionQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceHrPerfoHistoryQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceKPILimitQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceEvaluationCollagueQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceEvaluationDownwardQueryController.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/HrPerfoHistoryResponseDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPILimitDTO.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/EvaQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/HrPerfoHistoryQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KpiLimitQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/EvaQueryService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/HrPerfoService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/perfomance/command/application/service/AISummaryServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/perfomance/command/application/service/EvalutionCommandServiceTest.java
  perflow-backend/src/test/java/com/touchdown/perflowbackend/perfomance/command/application/service/HumanResourceCommandServiceTest.java
Labels: 💻 Chore

#297 fix: #296 dto 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/department/DepartmentCreateDTO.java
Labels: 🐞 Bug

#299 [feat/noti]: 알림 전체삭제 메소드 수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/application/service/NotificationCommandService.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/repository/NotificationCommandRepository.java
Labels: ✨ Feat

#301 [chore/#300] : 쿼리수정
  perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/SeverancePayQueryRepository.java
  perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeOvertimeQueryRepository.java
Labels: 💻 Chore

#302 [fix]: enum 추가
  perflow-backend/src/main/java/com/touchdown/perflowbackend/authority/domain/aggregate/AuthType.java
Labels: 🐞 Bug
